### PR TITLE
Aggregation

### PR DESCRIPTION
**Pull request by adityasundaram**
-Added aggregation capability 
- Added documentation for aggregation queries
- Date histogram aggregation with filters
- Group by non date fields
- Sub aggregation for sum,max,min,avg added but needs to be testing with number field changes in KG

### CODE REVIEW

**Comment by adityasundaram** [comment]
@szeke @GreatYYX

**Comment by GreatYYX** [comment]
need to remove the import `AggregateQueryProcessor`

**Comment by GreatYYX** [comment]
two more things to mention:

1. please format code in PEP8 next time.
2. be careful about typo: e.g., `conjuctive` --> `conjunctive`

**Comment by adityasundaram** [comment]
Ok @GreatYYX

**Pull request merged**
